export const Menu = 'menu/1';
export const Social ='website/social'
export const TopBar ='website/contacts'
export const Style ='website/style'
export const Gallery = 'website/gallery'
export const Blog = 'website/blog'
export const contactform ='contact'
export const subscribeform ='subscribe'
export const mediapartners ='topics/17/page/1/count/10/en'
